### ISSUE TITLE
Online documentation incomplete

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.ip.facedetect#3]
Hi,

the stable version of the documentation (on pythonhosted) is incomplete:
http://pythonhosted.org/bob.ip.facedetect/py_api.html

@tiagofrepereira2012 I assume that you uploaded that with the new ``new_version.py`` script, i.e., without rebuilding the package. Now you might understand, why I am not in favor of the new version of that script.

**Comment by tiagofrepereira2012** [comment]
Fixed (http://pythonhosted.org/bob.ip.facedetect/py_api.html), but this doesn't happend because that (update the docs without rebuild the package).
I had an issue with the sphinx-build and I had not observed that the HTML was incomplete.
